# permissions for end users to view cronrestarters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cron-restart
    app.kubernetes.io/managed-by: kustomize
  name: cronrestarter-viewer-role
rules:
- apiGroups:
  - autorestart.uni.com
  resources:
  - cronrestarters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autorestart.uni.com
  resources:
  - cronrestarters/status
  verbs:
  - get
