apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cron-restart
    app.kubernetes.io/managed-by: kustomize
  name: kubernetes-cronrestarter-controller
  namespace: kube-system
