apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-cronrestarter-controller
  namespace: "{{ .Values.namespace | toString }}"
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: cron-restart
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      imagePullSecrets:
        - name: default-jfrog-pull-secret
      restartPolicy: Always
      containers:
      - name: manager
        {{- if (eq "prod" .Values.activeEnv) }}
        image: "{{ .Values.image.prod.repository }}:{{ .Values.image.prod.tag }}"
        {{- else }}
        image: "{{ .Values.image.sit.repository }}:{{ .Values.image.sit.tag }}"
        {{- end }}
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Asia/Shanghai"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
{{ toYaml .Values.resources | nindent 10 }}
      serviceAccount: kubernetes-cronrestarter-controller
      terminationGracePeriodSeconds: 10
