---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-cronrestarter-controller-role
rules:
  - apiGroups:
      - autorestart.uni.com
    resources:
      - cronrestarters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - autorestart.uni.com
    resources:
      - cronrestarters/finalizers
    verbs:
      - update
  - apiGroups:
      - autorestart.uni.com
    resources:
      - cronrestarters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch